//! DSH Client — a Rust shell around the official DeepSeek Harness web GUI.
//!
//! Native macOS window (tao) hosting a WKWebView (wry) pointed at the local
//! `dsh web` server the worker boots. The dsh package itself is the official,
//! unmodified npm artifact; this shell only touches stable public interfaces
//! (the `dsh web` CLI, its printed URL, and the shared `~/.dsh` config).

mod runtime;
mod worker;

use std::process::Command;
use std::thread;
use std::time::Duration;

use tao::dpi::LogicalSize;
use tao::event::{Event, StartCause, WindowEvent};
use tao::event_loop::{ControlFlow, EventLoop};
use tao::window::WindowBuilder;
use tray_icon::menu::accelerator::{Accelerator, Code, Modifiers};
use tray_icon::menu::{
    Menu, MenuEvent, MenuItem, PredefinedMenuItem, Submenu,
};
use tray_icon::{Icon, MouseButton, MouseButtonState, TrayIconBuilder, TrayIconEvent};
use wry::{NewWindowResponse, WebView, WebViewBuilder};

use runtime::Runtime;
use worker::{UiMsg, Worker, WorkerCmd};

/// Tray icon is a 44x44 raw-RGBA template image generated by
/// `scripts/gen_icons.py`.
const TRAY_ICON_RGBA: &[u8] = include_bytes!("../assets/tray-template.rgba");
const TRAY_ICON_SIZE: u32 = 44;

fn main() {
    let rt = Runtime::new();
    rt.log(&format!("DSH Client v{} starting", env!("CARGO_PKG_VERSION")));

    let event_loop: EventLoop<UiMsg> = tao::event_loop::EventLoopBuilder::with_user_event().build();
    let proxy = event_loop.create_proxy();

    let window = WindowBuilder::new()
        .with_title("DeepSeek Harness")
        .with_inner_size(LogicalSize::new(1280.0, 820.0))
        .with_min_inner_size(LogicalSize::new(960.0, 620.0))
        .build(&event_loop)
        .expect("failed to create window");

    // ---- macOS application menu (Cmd+Q, Edit menu for WKWebView, etc.) ----
    let app_menu = build_app_menu();
    app_menu.init_for_nsapp();

    // ---- Menu bar tray ----
    let tray_menu = build_tray_menu();
    let tray = TrayIconBuilder::new()
        .with_icon(load_tray_icon())
        .with_icon_as_template(true)
        .with_tooltip("DSH Client — DeepSeek Harness 桌面客户端")
        .with_menu(Box::new(tray_menu))
        .with_menu_on_left_click(false)
        .build()
        .expect("failed to create tray icon");

    // ---- Bridge threads: menu/tray channels -> event loop ----
    let p_menu = proxy.clone();
    thread::spawn(move || loop {
        while let Ok(ev) = MenuEvent::receiver().try_recv() {
            let _ = p_menu.send_event(UiMsg::Menu(ev.id().0.clone()));
        }
        thread::sleep(Duration::from_millis(60));
    });
    let p_tray = proxy.clone();
    thread::spawn(move || loop {
        while let Ok(ev) = TrayIconEvent::receiver().try_recv() {
            if let TrayIconEvent::Click {
                button: MouseButton::Left,
                button_state: MouseButtonState::Up,
                ..
            } = ev
            {
                let _ = p_tray.send_event(UiMsg::TrayLeftClick);
            }
        }
        thread::sleep(Duration::from_millis(60));
    });

    // ---- Worker (runtime bootstrap + dsh process supervision) ----
    let worker = Worker::start(rt.clone(), proxy.clone());
    worker.send(WorkerCmd::Start);

    // ---- UI state ----
    let mut webview: Option<WebView> = None;
    let mut ready_url: Option<String> = None;
    let mut current_session: u64 = 0;
    let mut quitting = false;
    let mut restart_in_progress = false;
    let mut quick_deaths: u32 = 0;

    event_loop.run(move |event, _, control_flow| match event {
        Event::NewEvents(StartCause::Init) => {
            webview = Some(
                WebViewBuilder::new()
                    .with_html(loading_html())
                    .with_devtools(true)
                    .with_navigation_handler(|url| {
                        if url.starts_with("http://127.0.0.1")
                            || url.starts_with("http://localhost")
                            || url.starts_with("http://[::1]")
                        {
                            true
                        } else {
                            // External link (docs, etc.): hand off to the browser.
                            let _ = Command::new("open").arg(url).spawn();
                            false
                        }
                    })
                    .with_new_window_req_handler(|url, _features| {
                        let _ = Command::new("open").arg(url).spawn();
                        NewWindowResponse::Deny
                    })
                    .build(&window)
                    .expect("failed to build webview"),
            );
        }

        // Dock icon click re-opens the window.
        Event::Opened { .. } => window.set_visible(true),

        // Closing the window keeps the service running in the tray.
        Event::WindowEvent {
            event: WindowEvent::CloseRequested,
            ..
        } => window.set_visible(false),

        Event::UserEvent(msg) => match msg {
            UiMsg::Status(s) => {
                rt.log(&s);
                set_status(&webview, &s);
            }
            UiMsg::Ready { session, url } => {
                current_session = session;
                restart_in_progress = false;
                ready_url = Some(url.clone());
                rt.log(&format!("session {session} ready: {url}"));
                if let Some(w) = &webview {
                    let _ = w.load_url(&url);
                }
            }
            UiMsg::Exited {
                session,
                code,
                uptime_secs,
            } => {
                if quitting || session < current_session {
                    return;
                }
                current_session = session;
                ready_url = None;
                rt.log(&format!("session {session} exited: code={code:?} uptime={uptime_secs}s"));
                if restart_in_progress {
                    return;
                }
                if uptime_secs >= 60 {
                    quick_deaths = 0;
                }
                if uptime_secs < 60 && quick_deaths < 3 {
                    quick_deaths += 1;
                    set_status(&webview, "Harness 进程意外退出，正在自动重启…");
                    worker.send(WorkerCmd::Restart);
                } else {
                    show_error_page(
                        &webview,
                        "DeepSeek Harness 进程已退出。请通过菜单栏图标 → “重启 Harness” 重新启动。",
                    );
                }
            }
            UiMsg::UpdateInfo(s) => {
                rt.log(&s);
                if ready_url.is_none() {
                    set_status(&webview, &s);
                }
                let _ = tray.set_tooltip(Some(format!("DSH Client — {s}")));
            }
            UiMsg::Menu(id) => match id.as_str() {
                "toggle" => {
                    if window.is_visible() {
                        window.set_visible(false);
                    } else {
                        window.set_visible(true);
                    }
                }
                "reload" => {
                    if let Some(u) = &ready_url {
                        if let Some(w) = &webview {
                            let _ = w.load_url(u);
                        }
                    }
                }
                "devtools" => {
                    if let Some(w) = &webview {
                        w.open_devtools();
                    }
                }
                "check-update" => worker.send(WorkerCmd::CheckUpdate),
                "restart" => {
                    restart_in_progress = true;
                    quick_deaths = 0;
                    ready_url = None;
                    set_status(&webview, "正在重启 Harness…");
                    show_loading_page(&webview);
                    worker.send(WorkerCmd::Restart);
                }
                "open-config" => {
                    let dsh_home = std::env::var_os("DSH_HOME")
                        .map(std::path::PathBuf::from)
                        .unwrap_or_else(|| {
                            dirs::home_dir()
                                .map(|h| h.join(".dsh"))
                                .unwrap_or_else(|| "/".into())
                        });
                    let _ = Command::new("open").arg(dsh_home).spawn();
                }
                "quit" => {
                    quitting = true;
                    worker.send(WorkerCmd::Quit);
                }
                _ => {}
            },
            UiMsg::TrayLeftClick => {
                if window.is_visible() {
                    window.set_visible(false);
                } else {
                    window.set_visible(true);
                }
            }
            UiMsg::Bye => *control_flow = ControlFlow::Exit,
        },

        _ => {}
    });
}

// ---------------------------------------------------------------------------
// Menus
// ---------------------------------------------------------------------------

fn build_app_menu() -> Menu {
    let app = Submenu::with_items(
        "DSH Client",
        true,
        &[
            &PredefinedMenuItem::about(Some("关于 DSH Client"), None),
            &PredefinedMenuItem::separator(),
            &MenuItem::with_id(
                "quit",
                "退出 DSH Client",
                true,
                Some(Accelerator::new(Some(Modifiers::SUPER), Code::KeyQ)),
            ),
        ],
    )
    .unwrap();
    let edit = Submenu::with_items(
        "编辑",
        true,
        &[
            &PredefinedMenuItem::undo(None),
            &PredefinedMenuItem::redo(None),
            &PredefinedMenuItem::separator(),
            &PredefinedMenuItem::cut(None),
            &PredefinedMenuItem::copy(None),
            &PredefinedMenuItem::paste(None),
            &PredefinedMenuItem::select_all(None),
        ],
    )
    .unwrap();
    let view = Submenu::with_items(
        "视图",
        true,
        &[
            &MenuItem::with_id(
                "reload",
                "重新载入界面",
                true,
                Some(Accelerator::new(Some(Modifiers::SUPER), Code::KeyR)),
            ),
            &MenuItem::with_id(
                "devtools",
                "开发者工具",
                true,
                Some(Accelerator::new(
                    Some(Modifiers::SUPER | Modifiers::ALT),
                    Code::KeyI,
                )),
            ),
            &PredefinedMenuItem::separator(),
            &PredefinedMenuItem::minimize(None),
        ],
    )
    .unwrap();
    Menu::with_items(&[&app, &edit, &view]).unwrap()
}

fn build_tray_menu() -> Menu {
    Menu::with_items(&[
        &MenuItem::with_id("toggle", "显示 / 隐藏窗口", true, None),
        &PredefinedMenuItem::separator(),
        &MenuItem::with_id("check-update", "检查更新…", true, None),
        &MenuItem::with_id("restart", "重启 Harness", true, None),
        &MenuItem::with_id("open-config", "打开配置目录 (~/.dsh)", true, None),
        &PredefinedMenuItem::separator(),
        &MenuItem::with_id("quit", "退出 DSH Client", true, None),
    ])
    .unwrap()
}

fn load_tray_icon() -> Icon {
    Icon::from_rgba(TRAY_ICON_RGBA.to_vec(), TRAY_ICON_SIZE, TRAY_ICON_SIZE)
        .expect("invalid tray icon data")
}

// ---------------------------------------------------------------------------
// Loading / error pages
// ---------------------------------------------------------------------------

fn loading_html() -> String {
    r#"<!doctype html><html><head><meta charset="utf-8"><style>
body{margin:0;height:100vh;display:flex;flex-direction:column;align-items:center;justify-content:center;background:#0d1017;color:#c9d1d9;font-family:-apple-system,'PingFang SC','Helvetica Neue',sans-serif;-webkit-user-select:none;user-select:none}
.logo{font-size:15px;letter-spacing:.35em;color:#4d6bfe;font-weight:700}
.sub{font-size:12px;color:#6b7280;margin:10px 0 40px}
.spinner{width:34px;height:34px;border:3px solid #23262d;border-top-color:#4d6bfe;border-radius:50%;animation:s .9s linear infinite}
@keyframes s{to{transform:rotate(360deg)}}
#status{margin-top:30px;font-size:13px;color:#8b949e;max-width:72%;text-align:center;line-height:1.7}
.footer{position:fixed;bottom:20px;font-size:11px;color:#3f444d}
</style></head><body>
<div class="logo">DEEPSEEK HARNESS</div>
<div class="sub">DSH Client · Rust 外壳 · 官方 @deepseek-ai/dsh</div>
<div class="spinner"></div>
<div id="status">正在初始化…</div>
<div class="footer">关闭窗口后服务会在菜单栏继续运行 · 配置目录 ~/.dsh 与官方 CLI 共享</div>
</body></html>"#
        .to_string()
}

fn error_html(msg: &str) -> String {
    format!(
        r#"<!doctype html><html><head><meta charset="utf-8"><style>
body{{margin:0;height:100vh;display:flex;flex-direction:column;align-items:center;justify-content:center;background:#0d1017;color:#c9d1d9;font-family:-apple-system,'PingFang SC','Helvetica Neue',sans-serif;-webkit-user-select:none;user-select:none}}
.warn{{font-size:44px;color:#e5534b;margin-bottom:26px}}
#status{{font-size:14px;color:#a5adb8;max-width:64%;text-align:center;line-height:1.8}}
.hint{{margin-top:30px;font-size:12px;color:#6b7280}}
</style></head><body>
<div class="warn">⚠︎</div>
<div id="status">{msg}</div>
<div class="hint">通过菜单栏图标 → “重启 Harness” 重试；日志位于 ~/Library/Application Support/DSH Client/logs</div>
</body></html>"#
    )
}

fn show_loading_page(webview: &Option<WebView>) {
    if let Some(w) = webview {
        let _ = w.load_url(&format!(
            "data:text/html;charset=utf-8,{}",
            percent_encode_all(&loading_html())
        ));
    }
}

fn show_error_page(webview: &Option<WebView>, msg: &str) {
    if let Some(w) = webview {
        let _ = w.load_url(&format!(
            "data:text/html;charset=utf-8,{}",
            percent_encode_all(&error_html(msg))
        ));
    }
}

fn set_status(webview: &Option<WebView>, msg: &str) {
    if let Some(w) = webview {
        let _ = w.evaluate_script(&format!(
            "document.getElementById('status')&&(document.getElementById('status').textContent={});",
            js_string(msg)
        ));
    }
}

/// Escape a string for embedding inside a JavaScript string literal.
fn js_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// Percent-encode every byte — always a valid `data:` URL payload.
fn percent_encode_all(s: &str) -> String {
    s.as_bytes()
        .iter()
        .map(|b| format!("%{b:02X}"))
        .collect()
}
